# -*- coding: utf-8 -*-
"""723project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rC0V-3FycJwR3gkBYQoMngyoL8lQpq32
"""



"""# Project Overview"""



"""# Configuration"""

TIME_STEP = 2          # seconds per step
NUM_SLOTS = 30         # slots per road segment
GREEN_DURATION = 3     # timesteps per green phase
MAX_STEPS = 10

"""# Road Model"""

class Lane:
    def __init__(self, lane_id, start, end, direction):
        self.lane_id = lane_id
        self.start = start
        self.end = end
        self.direction = direction
        self.slots = [None] * NUM_SLOTS

    def __repr__(self):
        return f"Lane({self.lane_id}, {self.start}->{self.end}, dir={self.direction})"


class Intersection:
    def __init__(self, intersection_id, incoming_lanes):
        self.intersection_id = intersection_id
        self.incoming_lanes = incoming_lanes
        self.green_direction = None
        self.timer = 0

    def __repr__(self):
        return f"Intersection({self.intersection_id}, green={self.green_direction}, timer={self.timer})"

"""# Traffic Input"""

def traffic_case_1(timestep):
    return [
        {"vehicle_id": 1, "lane": "A_to_I1", "slot": 29, "direction": "N", "speed": 1, "wait_time": timestep}
    ]


def traffic_case_2(timestep):
    return [
        {"vehicle_id": 1, "lane": "A_to_I1", "slot": 29, "direction": "N", "speed": 1, "wait_time": timestep},
        {"vehicle_id": 2, "lane": "B_to_I1", "slot": 29, "direction": "E", "speed": 1, "wait_time": timestep}
    ]


def traffic_case_3(timestep):
    return []


def traffic_case_4(timestep):
    return [
        {"vehicle_id": 1, "lane": "B_to_I1", "slot": 29, "direction": "E", "speed": 1, "wait_time": timestep},
        {"vehicle_id": 2, "lane": "B_to_I1", "slot": 28, "direction": "E", "speed": 0, "wait_time": timestep},
        {"vehicle_id": 3, "lane": "B_to_I1", "slot": 27, "direction": "E", "speed": 0, "wait_time": timestep}
    ]


def traffic_case_5(timestep):
    vehicles = [
        {"vehicle_id": 1, "lane": "A_to_I1", "slot": 29, "direction": "N", "speed": 1, "wait_time": timestep},
        {"vehicle_id": 2, "lane": "A_to_I1", "slot": 28, "direction": "N", "speed": 0, "wait_time": timestep}
    ]

    if timestep >= 4:
        vehicles.append(
            {"vehicle_id": 3, "lane": "C_to_I1", "slot": 29, "direction": "S", "speed": 1, "wait_time": timestep}
        )

    return vehicles



"""# Signal Controller"""

DIRECTIONS = ["N", "E", "S", "W"]
MIN_GREEN_HOLD = 2

def compute_direction_scores(vehicles, starvation_counters):
    scores = {}

    for d in DIRECTIONS:
        waiting_count = sum(1 for v in vehicles if v["direction"] == d and v["slot"] == NUM_SLOTS - 1)
        max_wait = max(
            [v.get("wait_time", 0) for v in vehicles if v["direction"] == d] + [0]
        )
        starvation_bonus = starvation_counters[d]

        score = 3 * waiting_count + 2 * max_wait + starvation_bonus
        scores[d] = score

    return scores


DIRECTIONS = ["N", "E", "S", "W"]
MIN_GREEN_HOLD = 2
SWITCH_MARGIN = 2   # only switch if another direction is clearly better

def compute_direction_scores(vehicles, starvation_counters):
    scores = {}

    for d in DIRECTIONS:
        waiting_count = sum(
            1 for v in vehicles
            if v["direction"] == d and v["slot"] == NUM_SLOTS - 1
        )

        max_wait = max(
            [v.get("wait_time", 0) for v in vehicles if v["direction"] == d] + [0]
        )

        starvation_bonus = starvation_counters[d]

        # queue-aware score
        score = 3 * waiting_count + 2 * max_wait + starvation_bonus
        scores[d] = score

    return scores


def has_waiting_vehicle(vehicles, direction):
    return any(
        v["direction"] == direction and v["slot"] == NUM_SLOTS - 1
        for v in vehicles
    )


def update_signal_smart(intersection, vehicles, starvation_counters):
    scores = compute_direction_scores(vehicles, starvation_counters)
    total_demand = sum(scores.values())

    # -------------------------------------------------
    # 1) No traffic: keep current light, do not rotate
    # -------------------------------------------------
    if total_demand == 0:
        if intersection.green_direction is None:
            intersection.green_direction = "N"   # default initial direction
        intersection.timer += 1
        return

    # initialize first green if needed
    if intersection.green_direction is None:
        intersection.green_direction = max(scores, key=scores.get)
        intersection.timer = 0
        for d in DIRECTIONS:
            if d != intersection.green_direction:
                starvation_counters[d] += 1
        starvation_counters[intersection.green_direction] = 0
        return

    current_dir = intersection.green_direction
    current_score = scores[current_dir]
    best_dir = max(scores, key=scores.get)
    best_score = scores[best_dir]

    # -------------------------------------------------
    # 2) Minimum green hold
    # -------------------------------------------------
    if intersection.timer < MIN_GREEN_HOLD:
        intersection.timer += 1
        for d in DIRECTIONS:
            if d != current_dir:
                starvation_counters[d] += 1
        starvation_counters[current_dir] = 0
        return

    # -------------------------------------------------
    # 3) Green extension / queue-aware hold
    # Keep current green if:
    #    - current direction still has waiting cars
    #    - and no other direction is significantly better
    # -------------------------------------------------
    if has_waiting_vehicle(vehicles, current_dir) and best_score <= current_score + SWITCH_MARGIN:
        intersection.timer += 1
        for d in DIRECTIONS:
            if d != current_dir:
                starvation_counters[d] += 1
        starvation_counters[current_dir] = 0
        return

    # -------------------------------------------------
    # 4) Otherwise switch to best direction
    # -------------------------------------------------
    if best_dir != current_dir:
        intersection.green_direction = best_dir
        intersection.timer = 0
    else:
        intersection.timer += 1

    for d in DIRECTIONS:
        if d != intersection.green_direction:
            starvation_counters[d] += 1
    starvation_counters[intersection.green_direction] = 0

"""# Safety Checker"""

def get_crossing_vehicles(vehicles, intersection):
    crossing = []

    for v in vehicles:
        if (
            v["slot"] == NUM_SLOTS - 1
            and v["speed"] == 1
            and v["direction"] == intersection.green_direction
        ):
            crossing.append(v)

    # enforce at most one vehicle crossing per timestep
    return crossing[:1]

def check_collision(crossing_vehicles):
    return len(crossing_vehicles) > 1

def check_red_light(vehicle, intersection):
    return vehicle["direction"] != intersection.green_direction

"""# Simulation"""

def run_test_case(case_func, case_name, steps=10):
    # create one sample intersection
    i1 = Intersection(
        "I1",
        incoming_lanes=["A_to_I1", "B_to_I1", "C_to_I1", "D_to_I1"]
    )

    # initialize counters
    starvation_counters = {d: 0 for d in DIRECTIONS}
    collisions = 0
    red_light_violations = 0
    cars_passed = 0

    print(f"===== {case_name} =====")

    for t in range(steps):
        # get vehicles for this timestep
        vehicles = case_func(t)

        # update signal using smart controller
        update_signal_smart(i1, vehicles, starvation_counters)

        # determine which vehicles are allowed to cross
        crossing_vehicles = get_crossing_vehicles(vehicles, i1)

        # safety checks
        if check_collision(crossing_vehicles):
            collisions += 1

        for v in crossing_vehicles:
            if check_red_light(v, i1):
                red_light_violations += 1

        # throughput statistic
        cars_passed += len(crossing_vehicles)

        # print per-step result
        print(f"Time step {t}")
        print(f"  Green direction: {i1.green_direction}")
        print(f"  Vehicles: {vehicles}")
        print(f"  Crossing vehicles: {crossing_vehicles}")
        print(f"  Starvation counters: {starvation_counters}")
        print(f"  Total collisions so far: {collisions}")
        print(f"  Total red-light violations so far: {red_light_violations}")
        print(f"  Total vehicles passed so far: {cars_passed}")
        print("-" * 50)

    # final summary
    print("Final Summary")
    print(f"Collisions: {collisions}")
    print(f"Red-light violations: {red_light_violations}")
    print(f"Vehicles passed intersection: {cars_passed}")
    print("=" * 60)
    print()


# Run all 5 test cases
run_test_case(traffic_case_1, "Test Case 1: Single vehicle", steps=10)
run_test_case(traffic_case_2, "Test Case 2: Two conflicting vehicles", steps=10)
run_test_case(traffic_case_3, "Test Case 3: No traffic", steps=10)
run_test_case(traffic_case_4, "Test Case 4: Heavy eastbound traffic", steps=10)
run_test_case(traffic_case_5, "Test Case 5: Starvation prevention", steps=10)

"""# Test Results"""

